#nullable enable
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Hikari.Generator;

[Generator(LanguageNames.CSharp)]
internal class EntryPointGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            context.AddSource("EntryPointAttribute.g.cs",
"""
// <auto-generated>
#nullable enable
namespace Hikari;

[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
[global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
internal sealed class EntryPointAttribute : global::System.Attribute
{
    public EntryPointAttribute()
    {
    }
}

""");
        });

        var hkrProjcts = context.AdditionalTextsProvider
            .Where(f => Path.GetFileName(f.Path).EndsWith(".hkrproj"))
            .Select((f, ct) =>
            {
                ct.ThrowIfCancellationRequested();
                return f.GetText(ct)?.ToString();
            })
            .WithComparer(EqualityComparer<string?>.Default)
            .Select((text, ct) =>
            {
                ct.ThrowIfCancellationRequested();
                return (text != null) ? JsonSerializer.Deserialize<HkrProj>(text, HkrProj.DeserializeOptions) : null;
            })
            .Where(x => x != null)
            .Select((x, ct) => x!)
            .Collect();

        var methodsProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Hikari.EntryPointAttribute",
            static (node, _) => node is MethodDeclarationSyntax,
            static (context, ct) =>
            {
                ct.ThrowIfCancellationRequested();
                var method = (IMethodSymbol)context.TargetSymbol;
                var location = context.TargetNode.GetLocation();
                var fullyQualifiedName = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    + "." + method.Name;
                return (FullyQualifiedName: fullyQualifiedName, Location: location);
            })
            .Collect();

        context.RegisterSourceOutput(methodsProvider.Combine(hkrProjcts), static (context, provided) =>
        {
            var (methods, hkrProjects) = provided;
            if(methods.IsDefaultOrEmpty) {
                return;
            }
            if(methods.Length > 1) {
                foreach(var method in methods) {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.MultipleEntryPoints,
                        method.Location,
                        method.FullyQualifiedName));
                }
                return;
            }
            if(hkrProjects.IsDefaultOrEmpty) {
                return;
            }
            if(hkrProjects.Length > 1) {
                context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.MultipleProjectFiles,
                        null));
                return;
            }

            var entryMethod = methods[0].FullyQualifiedName;
            var proj = hkrProjects[0];
            context.AddSource("EditorEntryPoint.g.cs",
$$"""
// <auto-generated>
#nullable enable
namespace __HikariEditor
{
    internal sealed class __EditorEntryPoint
    {
        [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = "EditorEntryPoint")]
        public static void EditorEntryPoint()
        {
            global::System.Threading.Thread.CurrentThread.TrySetApartmentState(global::System.Threading.ApartmentState.STA);
            global::System.Environment.SetEnvironmentVariable("RUST_BACKTRACE", "1");
            global::Hikari.Engine.Run(engine =>
            {
                var config = new global::Hikari.ScreenConfig
                {
                    Title = @"{{proj.Window.Title}}",
                    Width = {{proj.Window.Width}},
                    Height = {{proj.Window.Height}},
                    Style = global::Hikari.WindowStyle.{{proj.Window.Style}},
                    PresentMode = global::Hikari.SurfacePresentMode.{{proj.Window.PresentMode}},
                };
                engine.CreateScreen(config, {{entryMethod}});
            });
        }
    }
}
""");
            context.AddSource("EntryPoint.g.cs",
$$"""
// <auto-generated>
#nullable enable
namespace Hikari
{
    internal sealed class __EntryPoint
    {
        [global::System.STAThread]
        private static void Main()
        {
            global::System.Environment.SetEnvironmentVariable("RUST_BACKTRACE", "1");
            global::Hikari.Engine.Run(engine =>
            {
                var config = new global::Hikari.ScreenConfig
                {
                    Title = @"{{proj.Window.Title}}",
                    Width = {{proj.Window.Width}},
                    Height = {{proj.Window.Height}},
                    Style = global::Hikari.WindowStyle.{{proj.Window.Style}},
                    PresentMode = global::Hikari.SurfacePresentMode.{{proj.Window.PresentMode}},
                };
                engine.CreateScreen(config, {{entryMethod}});
            });
        }
    }
}
""");
        });
    }

    public static void ParseJson(string json)
    {
        JsonSerializer.Deserialize<HkrProj>(json, HkrProj.DeserializeOptions);
    }
}

internal sealed class HkrProj
{
    public static JsonSerializerOptions DeserializeOptions { get; } = new JsonSerializerOptions
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true,
    };

    [JsonPropertyName("version")]
    public required string Version { get; set; }
    [JsonPropertyName("targetCsproj")]
    public required string TargetCsproj { get; set; }
    [JsonPropertyName("assemblyName")]
    public required string AssemblyName { get; set; }
    [JsonPropertyName("binDir")]
    public required string BinDir { get; set; }
    [JsonPropertyName("window")]
    public required WindowConfig Window { get; set; }
}

internal sealed class WindowConfig
{
    [JsonPropertyName("title")]
    public required string Title { get; set; }
    [JsonPropertyName("style")]
    public required string Style { get; set; }
    [JsonPropertyName("width")]
    public required uint Width { get; set; }
    [JsonPropertyName("height")]
    public required uint Height { get; set; }
    [JsonPropertyName("backend")]
    public string? Backend { get; set; }
    [JsonPropertyName("presentMode")]
    public required string PresentMode { get; set; }
}
